version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: bamboo
    versions:
    - 1.6.0
    - 1.7.0
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: timex
    versions:
    - 3.7.3
  - dependency-name: tesla
    versions:
    - 1.4.0
  - dependency-name: sentry
    versions:
    - 8.0.4
    - 8.0.5
  - dependency-name: excoveralls
    versions:
    - 0.13.4
    - 0.14.0
  - dependency-name: quantum
    versions:
    - 3.3.0
  - dependency-name: dataloader
    versions:
    - 1.0.7
    - 1.0.8
  - dependency-name: corsica
    versions:
    - 1.1.3
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix_html
    versions:
    - 2.14.3
  - dependency-name: plug
    versions:
    - 1.11.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
